apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: datagridallpv
  namespace: testdg
spec:
  groups:
  - name: datagridpvall-rule
    rules:
    - alert: datagridallpv
      expr: >
        sum(kubelet_volume_stats_used_bytes) by (persistentvolumeclaim)
        / sum(kubelet_volume_stats_capacity_bytes) by (persistentvolumeclaim)
        > 0.01
      labels:
        severity: critical
      annotations:
        description: PV '{{ $labels.persistentvolumeclaim }}' is running at {{ $value | humanizePercentage }} of its capacit
