apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: datagridallpv
  namespace: testdg
spec:
  groups:
  - name: datagridpv-rule
    rules:
    - alert: datagridpv 
      expr: >
        sum(kubelet_volume_stats_used_bytes by (persistentvolumeclaim))
        / sum(kubelet_volume_stats_capacity_bytes by (persistentvolumeclaim))
        > 0.01
      labels:
        severity: critical
      annotations:
        description: datagrid PV disk usage is greater than 80%
