---
- name: EDA | AlertManager | Listen for events from AlertManager
  hosts: localhost

  sources:
    - name: listen for alerts
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5001

  rules:
    - name: debug with multiple messages
      condition: event.payload is defined
      action:
        debug:
          msg:
          - "Message 1 {{ event }}"
          - Second Message
