---
- name: EDA | AlertManager | Listen for events from AlertManager
  hosts: localhost

  sources:
    - name: listen for alerts
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5001

  rules:
    - name: debug with multiple messages
      condition: event.payload.status == "firing"
      action:
        - run_job_template:
            name: "[EDA] Alertmanager playbook"
            organization: Default
            job_args:
              extra_vars:
                alerts: "{{ event.payload.alerts }}"
                alertStatus: "{{ event.payload.status }}"
