---
- name: EDA | AlertManager | Listen for events from AlertManager
  hosts: localhost

  sources:
    - name: listen for alerts
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5001

  rules:
    - name: EDA | AlertManager | Resize PVC
      condition: event.payload.status == "firing"
      actions:
        - run_job_template:
            name: "Resize PVC"
            organization: Default
            job_args:
              extra_vars:
                alerts: "{{ ansible_eda.event.payload.alerts }}"
                alertStatus: "{{ ansible_eda.event.payload.status }}"
