---
- name: EDA-Alertmanager-Example alert resolution
  hosts: localhost
  tasks:
    - name: Handle new firing alert
      when: alertStatus == "firing"
      block:
        - name: Debug message
          ansible.builtin.debug:
            msg:
              - "The event {{ alerts.labels.alertname }} just triggered"

        - name: Remediating issue to resolve the alert
          ansible.builtin.debug:
            msg: Trying to solve {{ alerts.labels.alertname }}

    - name: Notify resolution
      ansible.builtin.debug:
        msg: "The event {{ alerts.labels.alertname }} was just resolved by Ansible Event Driven!"
      when: alertStatus == "resolved"
