---
- name: Resize PVC
  hosts: localhost
  tasks:
    - name: Handle new firing alert
      when: alertStatus == 'firing'
      block:
        - name: Debug message
          ansible.builtin.debug:
            msg:
              - "The event {{ item.labels.alertName }} just triggered on {{ item.labels.alertTargetHosts }}"
              - "Alert body is: {{ item.labels.alertMessage }}"

