---
- name: Ansible Playbook for Resizing PVC
  hosts: localhost
  connection: local
  gather_facts: yes
  collections:
    - community.general
  tasks:

        - name: Increase PVC Size
          kubernetes.core.k8s:
            state: present
            definition:
              apiVersion: snapshot.storage.k8s.io/v1
              kind: VolumeSnapshot
              metadata:
                name: "{{ ansible_eda.event.resource.metadata.name }}-snapshot-{{ ansible_date_time.date }}"
                namespace: "{{ ansible_eda.event.resource.metadata.namespace }}"
              spec:
                source:
                  persistentVolumeClaimName: "{{ ansible_eda.event.resource.metadata.name }}"

      rescue:

        - name: event debug
          ansible.builtin.debug:
            var: pvc_status

        - name: Debug status
          ansible.builtin.debug:
            msg: "{{ pvc_status.resources[0].status.phase }}"

        - name: Handle PVC not Bound
          ansible.builtin.debug:
            msg: "Status 'Bound' was never achieved for the Persistent Volume Claim {{ ansible_eda.event.resource.metadata.name }}"

    - name: Get PVC Details
      kubernetes.core.k8s_info:
        api_version: snapshot.storage.k8s.io/v1
        kind: VolumeSnapshot
        namespace: "{{ ansible_eda.event.resource.metadata.namespace }}"
      register: volumesnapshot_details

    - name: Debug message for PVC
      ansible.builtin.debug:
        msg: "Name: {{ item.name }}, Namespace: {{ item.namespace }}"
      loop: "{{ volumesnapshot_details | community.general.json_query('resources[*].metadata') }}"
      loop_control:
        label: "Name: {{ item.name }}, Namespace: {{ item.namespace }}"
